name: encourage developers

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Send comment
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;

            if (prNumber % 5 === 0) {
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'いい調子！🎉引き続き開発していこう！🚀'
              })
            }


